Revert "feat: setup persisted state across page reloads"
This reverts commit 3182ec830185981d7efab6b081437432c72aa81b.

I see the following, persisting error on production:
```
DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
    at Object.appendChild (https://app.journcoin.de/_nuxt/861d8ff.js:2:41276)
    at m (https://app.journcoin.de/_nuxt/861d8ff.js:2:54199)
    at v (https://app.journcoin.de/_nuxt/861d8ff.js:2:53936)
    at _ (https://app.journcoin.de/_nuxt/861d8ff.js:2:54285)
    at P (https://app.journcoin.de/_nuxt/861d8ff.js:2:57671)
    at P (https://app.journcoin.de/_nuxt/861d8ff.js:2:57606)
    at P (https://app.journcoin.de/_nuxt/861d8ff.js:2:57606)
    at P (https://app.journcoin.de/_nuxt/861d8ff.js:2:57606)
    at P (https://app.journcoin.de/_nuxt/861d8ff.js:2:57606)
    at P (https://app.journcoin.de/_nuxt/861d8ff.js:2:57606)
Promise.catch (async)
(anonymous) @ 99a1035.js:2
(anonymous) @ 99a1035.js:2
c @ b0ae26f.js:1
240 @ 28ecf30.js:1
c @ b0ae26f.js:1
t @ b0ae26f.js:1
r @ b0ae26f.js:1
(anonymous) @ 28ecf30.js:1
```

The QR scanner does not show up.